baseURL: /
theme: hugo-apero
languageCode: en
title: Pao Corrales
author: Pao Corrales
copyright: ''
googleAnalytics: 'G-328E3YGZP0'
publishDir: "docs"
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes 
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: 'hex-colors'
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/favicon_big.png
  mainSections:
    - blog
    - project
    - courses
  math:
    renderer: katex
  navallcaps: yes
  orgLocal: Argentina
  orgName: 
  sharing_image: /img/forecast_factory.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/paocorrales
    - icon: instagram
      icon_pack: fab
      url: https://www.instagram.com/paobcorrales
    - icon: mastodon
      icon_pack: fab
      url: https://fosstodon.org/@paocorrales
    - icon: orcid
      icon_pack: ai
      url: http://orcid.org/0000-0003-1923-9129
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: ''
  twitter: papbcorrales
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: paocorrales/paocorrales.github.io
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 2
    - name: Contributors
      title: Contributors
      url: /contributors/
      weight: 3
  header:
    - name: About
      title: About
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
    - name: Courses
      title: Courses
      url: /courses/
      weight: 3
    - name: Projects
      title: Projects Porfolio
      url: /project/
      weight: 4
    - name: Publications
      title: Publications
      url: /publications/
      weight: 6
    - name: Talks
      title: Talks
      url: /talk/
      weight: 6
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
